### ISSUE TITLE
TypeError: Argument 4 

### ISSUE THREAD

**Issue by baluballa** [PaulLereverend/NextcloudDuplicateFinder#80]
When running `occ -v duplicates:find-all -u [user_name] -p ./Photos`  on linx with nextcloud version 24.01 I get this error:
```
Start searching files for user_name in path /user_name/files/./Photos
An unhandled exception has been thrown:

TypeError: Argument 4 passed to OC\Files\Utils\Scanner::__construct() must implement interface Psr\Log\LoggerInterface, instance of OC\AppFramework\Logger given, called in /.../nextcloud/apps/duplicatefinder/lib/Utils/ScannerUtil.php on line 78 and defined in /.../nextcloud/lib/private/Files/Utils/Scanner.php:95
Stack trace:
#0 /.../nextcloud/apps/duplicatefinder/lib/Utils/ScannerUtil.php(78): OC\Files\Utils\Scanner->__construct()
#1 /.../nextcloud/apps/duplicatefinder/lib/Utils/ScannerUtil.php(68): OCA\DuplicateFinder\Utils\ScannerUtil->initializeScanner()
#2 /.../nextcloud/apps/duplicatefinder/lib/Service/FileInfoService.php(256): OCA\DuplicateFinder\Utils\ScannerUtil->scan()
#3 /.../nextcloud/apps/duplicatefinder/lib/Command/FindDuplicates.php(162): OCA\DuplicateFinder\Service\FileInfoService->scanFiles()
#4 /.../nextcloud/apps/duplicatefinder/lib/Command/FindDuplicates.php(133): OCA\DuplicateFinder\Command\FindDuplicates->findDuplicates()
#5 /.../nextcloud/apps/duplicatefinder/lib/Command/FindDuplicates.php(109): OCA\DuplicateFinder\Command\FindDuplicates->findDuplicatesForUsers()
#6 /.../nextcloud/3rdparty/symfony/console/Command/Command.php(255): OCA\DuplicateFinder\Command\FindDuplicates->execute()
#7 /.../nextcloud/core/Command/Base.php(168): Symfony\Component\Console\Command\Command->run()
#8 /.../nextcloud/3rdparty/symfony/console/Application.php(1009): OC\Core\Command\Base->run()
#9 /.../nextcloud/3rdparty/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#10 /.../nextcloud/3rdparty/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun()
#11 /.../nextcloud/lib/private/Console/Application.php(211): Symfony\Component\Console\Application->run()
#12 /.../nextcloud/console.php(99): OC\Console\Application->run()
#13 /.../nextcloud/occ(11): require_once('/var/www/html/c...')
#14 {main}
```
Not sure how to grab duplicatefinder version, but it is latest "De Dato".

**Comment by mtargosz** [comment]
Same for me with NC 24 and `duplicatefinder` version 	`0.0.14` 

_( @baluballa version can be found in UI under `settings/apps/installed/duplicatefinder` )_
