### ISSUE TITLE
App crash when run "occ duplicates:find-all"

### ISSUE THREAD

**Issue by karankevich-aleksey** [PaulLereverend/NextcloudDuplicateFinder#82]
Hi! I have install app in this environment: 

- NEXTCLOUD: 24.0.1
- PHP: 7.4.30
- APAHCE: 2.4.37

When i try to exec "occ duplicates:find-all" i got an error:

`An unhandled exception has been thrown:
TypeError: Argument 4 passed to OC\Files\Utils\Scanner::__construct() must implement interface Psr\Log\LoggerInterface, instance of OC\AppFramework\Logger given, called in /var/www/html/nextcloud/apps/duplicatefinder/lib/Utils/ScannerUtil.php on line 78 and defined in /var/www/html/nextcloud/lib/private/Files/Utils/Scanner.php:95
Stack trace:

#0 /var/www/html/nextcloud/apps/duplicatefinder/lib/Utils/ScannerUtil.php(78): OC\Files\Utils\Scanner->__construct()

#1 /var/www/html/nextcloud/apps/duplicatefinder/lib/Utils/ScannerUtil.php(68): OCA\DuplicateFinder\Utils\ScannerUtil->initializeScanner()

#2 /var/www/html/nextcloud/apps/duplicatefinder/lib/Service/FileInfoService.php(256): OCA\DuplicateFinder\Utils\ScannerUtil->scan()

#3 /var/www/html/nextcloud/apps/duplicatefinder/lib/Command/FindDuplicates.php(152): OCA\DuplicateFinder\Service\FileInfoService->scanFiles()

#4 /var/www/html/nextcloud/apps/duplicatefinder/lib/Command/FindDuplicates.php(133): OCA\DuplicateFinder\Command\FindDuplicates->findDuplicates()

#5 /var/www/html/nextcloud/apps/duplicatefinder/lib/Command/FindDuplicates.php(109): OCA\DuplicateFinder\Command\FindDuplicates->findDuplicatesForUsers()

#6 /var/www/html/nextcloud/3rdparty/symfony/console/Command/Command.php(255): OCA\DuplicateFinder\Command\FindDuplicates->execute()

#7 /var/www/html/nextcloud/core/Command/Base.php(168): Symfony\Component\Console\Command\Command->run()

#8 /var/www/html/nextcloud/3rdparty/symfony/console/Application.php(1009): OC\Core\Command\Base->run()

#9 /var/www/html/nextcloud/3rdparty/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()

#10 /var/www/html/nextcloud/3rdparty/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun()

#11 /var/www/html/nextcloud/lib/private/Console/Application.php(211): Symfony\Component\Console\Application->run()

#12 /var/www/html/nextcloud/console.php(99): OC\Console\Application->run()

#13 /var/www/html/nextcloud/occ(11): require_once('/var/www/html/n...')

#14 {main}`

**Comment by Jott-Emm** [comment]
It's exact the same error for me. My System is nextcloud 24.0.1, OS Linux 5.15.0-40-generic x86_64 (Ubuntu 22.04), Apache 2.4.52, PHP 8.1.2, duplicatefinder 0.14.
How can that be fixed?
