### ISSUE TITLE
Start searching files for azathoth in path /azathoth/files An unhandled exception has been thrown:

### ISSUE THREAD

**Issue by azathoth3** [PaulLereverend/NextcloudDuplicateFinder#84]
TypeError: Argument 4 passed to OC\Files\Utils\Scanner::__construct() must implement interface Psr\Log\LoggerInterface, instance of OC\AppFramework\Logger given, called in /var/www/html/apps/duplicatefinder/lib/Utils/ScannerUtil.php on line 78 and defined in /var/www/html/lib/private/Files/Utils/Scanner.php:95
Stack trace:

**Comment by Gagootron** [comment]
Got the same errors. Some more info on my system:
OS: Alpine 3.15.4
Docker version: 20.10.14
Nextcloud version: 24.0.0
Nextcloud image hash: sha256:a4becf970bceae40db6357aded92a98ba76f220e6359f6e99ae5fb7a93dec08a
Plugin version: 0.0.14
PHP version (in container): 8.0.18

Command: ./occ duplicates:find-all
pwd: /var/www/html
This command has been run as the 1006:1007 user, but i use it instead of the www-data user.

Command output:
`I have no name!@ae86dc3217be:/var/www/html$ ./occ duplicates:find-all
Start searching files for admin in path /admin/files
An unhandled exception has been thrown:
TypeError: OC\Files\Utils\Scanner::__construct(): Argument #4 ($logger) must be of type Psr\Log\LoggerInterface, OC\AppFramework\Logger given, called in /var/www/html/custom_apps/duplicatefinder/lib/Utils/ScannerUtil.php on line 78 and defined in /var/ww
w/html/lib/private/Files/Utils/Scanner.php:95
Stack trace:
#0 /var/www/html/custom_apps/duplicatefinder/lib/Utils/ScannerUtil.php(78): OC\Files\Utils\Scanner->__construct('admin', Object(OC\DB\ConnectionAdapter), Object(OC\EventDispatcher\EventDispatcher), Object(OC\AppFramework\Logger))
#1 /var/www/html/custom_apps/duplicatefinder/lib/Utils/ScannerUtil.php(68): OCA\DuplicateFinder\Utils\ScannerUtil->initializeScanner('admin', false)
#2 /var/www/html/custom_apps/duplicatefinder/lib/Service/FileInfoService.php(256): OCA\DuplicateFinder\Utils\ScannerUtil->scan('admin', '/admin/files')
#3 /var/www/html/custom_apps/duplicatefinder/lib/Command/FindDuplicates.php(152): OCA\DuplicateFinder\Service\FileInfoService->scanFiles('admin', NULL, Object(Closure), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /var/www/html/custom_apps/duplicatefinder/lib/Command/FindDuplicates.php(112): OCA\DuplicateFinder\Command\FindDuplicates->findDuplicates('admin')
#5 /var/www/html/lib/private/User/Manager.php(551): OCA\DuplicateFinder\Command\FindDuplicates->OCA\DuplicateFinder\Command\{closure}(Object(OC\User\User))
#6 /var/www/html/custom_apps/duplicatefinder/lib/Command/FindDuplicates.php(113): OC\User\Manager->callForAllUsers(Object(Closure))
#7 /var/www/html/3rdparty/symfony/console/Command/Command.php(255): OCA\DuplicateFinder\Command\FindDuplicates->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /var/www/html/core/Command/Base.php(168): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /var/www/html/3rdparty/symfony/console/Application.php(1009): OC\Core\Command\Base->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /var/www/html/3rdparty/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(OCA\DuplicateFinder\Command\FindDuplicates), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\O
utput\ConsoleOutput))
#11 /var/www/html/3rdparty/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /var/www/html/lib/private/Console/Application.php(211): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /var/www/html/console.php(99): OC\Console\Application->run()
#14 /var/www/html/occ(11): require_once('/var/www/html/c...')
#15 {main}`
